security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt))/
            security: false
        main:
            pattern:    .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path:            /home
            logout:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path:            /login
            remember_me:
                key:    %secret%
                lifetime: 300000000
                path:     /
                domain:   ~
            logout:       true
            anonymous:    true

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email